/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as PlansSlugRouteImport } from './routes/plans.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansSlugRoute = PlansSlugRouteImport.update({
  id: '/plans/$slug',
  path: '/plans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/team/$slug': typeof TeamSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/team/$slug': typeof TeamSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terms': typeof TermsRoute
  '/plans/$slug': typeof PlansSlugRoute
  '/team/$slug': typeof TeamSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/terms' | '/plans/$slug' | '/team/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/terms' | '/plans/$slug' | '/team/$slug'
  id: '__root__' | '/' | '/terms' | '/plans/$slug' | '/team/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TermsRoute: typeof TermsRoute
  PlansSlugRoute: typeof PlansSlugRoute
  TeamSlugRoute: typeof TeamSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$slug': {
      id: '/plans/$slug'
      path: '/plans/$slug'
      fullPath: '/plans/$slug'
      preLoaderRoute: typeof PlansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TermsRoute: TermsRoute,
  PlansSlugRoute: PlansSlugRoute,
  TeamSlugRoute: TeamSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
